[build]
  command = "npm install"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/index.js"
  status = 200

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

[[redirects]]
  from = "/app"
  to = "/public/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.js"
  status = 200
